export const errorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  FORBIDDEN_NOT_OWNER: 'FORBIDDEN_NOT_OWNER',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = typeof errorCodes[keyof typeof errorCodes];
